<?xml version="1.0" encoding="UTF-8"?>
<Database Name="teamyar" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="customers" Member="Customers">
    <Type Name="Customer">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="city" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="age" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="warehouses" Member="Warehouses">
    <Type Name="Warehouse">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="products" Member="Products">
    <Type Name="Product">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="brand" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="color" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="model" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="features" Type="System.String" DbType="NText" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="sales_invoices" Member="SalesInvoices">
    <Type Name="SalesInvoice">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="customer_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="warehouse_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="product_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="popular_products" Member="PopularProducts">
    <Type Name="PopularProduct">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="product_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>